trigger:
- main

variables:
  # Change these for your env
  imageRepository: 'streamlit-app'
  containerRegistry: 'agratasacr123.azurecr.io'     # ACR login server
  dockerRegistryServiceConnection: 'acr-sc'         # Service connection name for ACR
  webAppName: 'agratas-streamlit-web'               # Your Web App name
  resourceGroupName: 'agratas-rg'                   # For AZ CLI (optional)
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build & Push'
  jobs:
  - job: BuildAndPush
    displayName: 'Build Docker image and push to ACR'
    steps:
    - task: Docker@2
      displayName: 'Build and push image'
      inputs:
        command: buildAndPush
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        dockerfile: '**/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: |
          $(tag)

    - script: |
        echo "Built image: $(containerRegistry)/$(imageRepository):$(tag)"
      displayName: 'Show image name'

- stage: Deploy
  displayName: 'Deploy to Web App'
  dependsOn: Build
  jobs:
  - job: DeployToWebApp
    displayName: 'Deploy container to Azure Web App'
    steps:
    - task: AzureWebAppContainer@2
      displayName: 'Deploy container to Web App'
      inputs:
        azureSubscription: 'azure-rm-sc'
        appName: '$(webAppName)'
        containers: '$(containerRegistry)/$(imageRepository):$(tag)'

    - task: AzureCLI@2
      displayName: 'Ensure WEBSITES_PORT is set'
      inputs:
        azureSubscription: 'azure-rm-sc'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az webapp config appsettings set \
            -g '$(resourceGroupName)' -n '$(webAppName)' \
            --settings WEBSITES_PORT=8501 PORT=8501
